/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppBackupRouteImport } from './routes/_app/backup'
import { Route as AppCoursesRouteImport } from './routes/_app/courses'
import { Route as AppCvRouteImport } from './routes/_app/cv'
import { Route as AppVarsitiesRouteImport } from './routes/_app/varsities'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupRoute = AppBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppCvRoute = AppCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AppRoute,
} as any)
const AppVarsitiesRoute = AppVarsitiesRouteImport.update({
  id: '/varsities',
  path: '/varsities',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AppAccountRoute
  '/backup': typeof AppBackupRoute
  '/courses': typeof AppCoursesRoute
  '/cv': typeof AppCvRoute
  '/varsities': typeof AppVarsitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AppAccountRoute
  '/backup': typeof AppBackupRoute
  '/courses': typeof AppCoursesRoute
  '/cv': typeof AppCvRoute
  '/varsities': typeof AppVarsitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/backup': typeof AppBackupRoute
  '/_app/courses': typeof AppCoursesRoute
  '/_app/cv': typeof AppCvRoute
  '/_app/varsities': typeof AppVarsitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/account'
    | '/backup'
    | '/courses'
    | '/cv'
    | '/varsities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/account'
    | '/backup'
    | '/courses'
    | '/cv'
    | '/varsities'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/account'
    | '/_app/backup'
    | '/_app/courses'
    | '/_app/cv'
    | '/_app/varsities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backup': {
      id: '/_app/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AppBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cv': {
      id: '/_app/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof AppCvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/varsities': {
      id: '/_app/varsities'
      path: '/varsities'
      fullPath: '/varsities'
      preLoaderRoute: typeof AppVarsitiesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppBackupRoute: typeof AppBackupRoute
  AppCoursesRoute: typeof AppCoursesRoute
  AppCvRoute: typeof AppCvRoute
  AppVarsitiesRoute: typeof AppVarsitiesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppBackupRoute: AppBackupRoute,
  AppCoursesRoute: AppCoursesRoute,
  AppCvRoute: AppCvRoute,
  AppVarsitiesRoute: AppVarsitiesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
